# Generated by Django 3.2.8 on 2021-10-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_allergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergy',
        ),
    ]
